### ISSUE TITLE
Headercolor is random

### ISSUE THREAD

**Issue by denis-mrd** [BOCOVO/db-schema-visualizer#30]
Hello! Thank you for this plugin!
Could you please set the table's color according to table settings (https://dbml.dbdiagram.io/docs/#table-settings)? 

```
Table users [headercolor: #3498DB] {
    id integer [primary key]
    username varchar(255) [not null, unique]
}
```

It's also would be nice to save position of existing tables on canvas)

**Comment by BOCOVO** [comment]
Hello @denis-mrd !
Thanks for the interesting feedback. 

I note two things to add 
- the use of the table color defined in the DBML code
- saving table positions when exiting a file so that they can be restored when returning to it.

But I think that the second ( `saving table positions` ) will be implemented before the first, as its absence makes the experience a little unpleasant.

**Comment by BOCOVO** [comment]
> @BOCOVO you can use this repo as an example: https://github.com/denis-mrd/dbdiagram-oss

Interesting ! Thank you @denis-mrd

**Comment by BOCOVO** [comment]
Hey @denis-mrd !
I've just released the tables position saving in the 0.1.0 version 🔥

**Comment by denis-mrd** [comment]
Yeah, it is working! Awesome!
Could you please implement "the headercolor" as well?)

**Comment by tv-long** [comment]
Hi,
I just make a PR for supporting headercolor of table setting.
Hope it helps

**Comment by BOCOVO** [comment]
Hi @tv-long !

I just merge your pull request add also release the feature in the 0.2.0 version 🔥 . The feature help improve the project.
Thank you a lot. 

Looking forward to more contributions from you in the future !

**Comment by BOCOVO** [comment]
Hi @tv-long !

I just merge your pull request add also release the feature in the 0.2.0 version 🔥 . The feature help improve the project.
Thank you a lot.

Looking forward to more contributions from you in the future !

**Comment by denis-mrd** [comment]
🔥🔥🔥
Thank you guys very much! I'm going to switch to developing a model with this tool next month
