### ISSUE TITLE
table name is trucated or column name is on top of datatype for long field names

### ISSUE THREAD

**Issue by desoumyadeep** [BOCOVO/db-schema-visualizer#33]
As the tables are rendered in Preview as fixed size and cannot be resized, the texts are either truncated or are one on top of other if the column name or the table name is long.

> Please add Table Resize / Autosize

![Screenshot 2024-05-07 at 9 22 49 AM](https://github.com/BOCOVO/db-schema-visualizer/assets/87954186/09cd3e72-81d6-4a22-9c05-76957b83ac8a)

**Comment by BOCOVO** [comment]
Hello @desoumyadeep !

Indeed, table width is fixed in the release, but I'm already working ( https://github.com/BOCOVO/db-schema-visualizer/pull/32 ) on adapting it to its content (autosize).
This improvement will be available soon 🔥 .
