### ISSUE TITLE
No easy way to get the extension

### ISSUE THREAD

**Issue by ryanw3b3r** [BOCOVO/db-schema-visualizer#39]
Hi,

Thanks for all your hard work! I don't have an issue with the visualizer, but rather I have an issue with info in the `readme` file. It took me way too long to find this extension on VS Code marketplace, so it should be mentioned where to find it: https://marketplace.visualstudio.com/items?itemName=bocovo.dbml-erd-visualizer

**Comment by BOCOVO** [comment]
Hi @ryanw3b3r !

Oh, that's true. I'll update the Readme. 
Thanks
