### ISSUE TITLE
Table blocks not wide enough

### ISSUE THREAD

**Issue by ryanw3b3r** [BOCOVO/db-schema-visualizer#40]
Is there any way to control the size of table blocks in preview? We have a table with column `email_verified_at` of type `timestamp` and both words are overlapping making them unreadable. Column is just not wide enough.

<img width="152" alt="overlap" src="https://github.com/BOCOVO/db-schema-visualizer/assets/5539351/ac319346-381f-4382-b3d4-bff61d86bb87">

**Comment by BOCOVO** [comment]
Hi @ryanw3b3r !

That is already fixed, but not already released, which will be done soon.

**Comment by BOCOVO** [comment]
I've just released it in version 0.1.0.

**Comment by BOCOVO** [comment]
I've just released it in version 0.1.0.
