### ISSUE TITLE
[Feature Proposal] Ability to save the positions of each table

### ISSUE THREAD

**Issue by LargatSeif** [BOCOVO/db-schema-visualizer#41]
Hey 👋 ,
First thanks for this great tool 🙏🏻.
Can you please add the ability to store somewhere the positions of each table (for example in a layout.json so we can load on each diagram)
Thanks in advance.

**Comment by BOCOVO** [comment]
Hey, this was already done.
I've just released it in version 0.1.0 🔥

**Comment by kiryasolod** [comment]
Thanks for adding this feature, it really helps! But could you consider saving it to a .vscode directory, to some file instead of Local/Session storage of VSCode itself? It would be much more convenient because we could share positions of tables between developers using git, for example
