### ISSUE TITLE
Plugin behaves weird  if there is similar table names in different schema

### ISSUE THREAD

**Issue by xemuliam** [BOCOVO/db-schema-visualizer#53]
## What's wrong 
Plugin behaves weird  if there is similar table names in different schema.
Tables are underplayed each other.
You can see two tables by dragging table on canvas. Both tables will be visible until you release MLB and don't move cursor.
If MLB released and cursor has been moved then one table disappears.
Then you can repeat above exercise as many times as you want.
Auto-arrange doesn't help at all.

## Expected behaviour
To see all objects from all schemas. The same name in different schemas should not affect any process.

## How to reproduce:

Actions are decribed above.

Here is the code.

```
table stage.test {
  field1 integer
}

table core.test {
  field2 integer
}
```

**Comment by BOCOVO** [comment]
Hello @xemuliam !

Thank you for submitting the issue and for your clear description.
I think I have an idea of the problem.
I solve it as soon as possible.

**Comment by BOCOVO** [comment]
Hello @xemuliam !
The issue was fixed, and a new version was released for that (`v.0.3.1`).
It would be great to have your feedback.

**Comment by xemuliam** [comment]
Hi @BOCOVO ,

checked and LGTM.

Thanks!

**Comment by BOCOVO** [comment]
> Hi @BOCOVO ,
> 
> checked and LGTM.
> 
> Thanks!

Thank you for the feedback.
