### ISSUE TITLE
Table names is being truncated.

### ISSUE THREAD

**Issue by rennie-moodley** [BOCOVO/db-schema-visualizer#55]
**Describe the bug**
When adding a table name that is longer than the (ColumnName + DataType), the full table name does NOT get shown.

**To Reproduce**
1. Create a .dbml file.
2. Add the following DBML content to that file.
3. `Table dbo.tb_FairlyLongTableName {
  TestID INT
  Name NVARCHAR(100)
  Value NVARCHAR(300)
  CreatedDate DATETIME
  ModifiedDate DATETIME
}`
4. Preview using the extension.

**Expected behavior**
To see the full table name.

**Screenshots**

**Desktop (please complete the following information):**
 - VSCode on windows.
 - Version [0.3.2] of the extension.

**Comment by BOCOVO** [comment]
Hello @rennie-moodley !

Thank you for reporting the problem.
I also already notice that. 
I'll fix it in the next few days.

**Comment by BOCOVO** [comment]
Hello @rennie-moodley !
This is fixed here https://github.com/BOCOVO/db-schema-visualizer/pull/58
