### ISSUE TITLE
Small but prominent typo

### ISSUE THREAD

**Issue by ptyork** [BOCOVO/db-schema-visualizer#57]
Insignificant but it caught my eye since it's front and center. The DBML preview window tab says "DBLM Diagram Preview".

Simple fix to two lines in packages/dbml-vs-code-extension/extension/constants/index.ts

**Comment by BOCOVO** [comment]
Hello @ptyork !
Oh, thank you for catching this.
I will fix it as soon as possible.

**Comment by BOCOVO** [comment]
Fixed and released in the v0.3.3
